language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t romantuom/ci-cd-with-docker -f ./ci-cd-with-docker/Dockerfile.dev ./ci-cd-with-docker

script:
  - docker run -e CI=true romantuom/ci-cd-with-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-926020876883"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
