version: '3'
services:
    postgres:
        image: 'postgres:latest'
        env_file: ./.env
    redis:
        image: 'redis:latest'
        env_file: ./.env
    nginx:
        depends_on:
            - fiboserver
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
    fiboserver:
        env_file: ./.env
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /server/node_modules
            - ./server:/server
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /client/node_modules
            - ./client:/client
    worker:
        env_file: ./.env
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /worker/node_modules
            - ./worker:/worker