version: '3'
services:
    postgres:
        image: 'postgres:latest'
        env_file: ./.env
    redis:
        image: 'redis:latest'
        env_file: ./.env
    fiboserver:
        env_file: ./.env
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /server/node_modules
            - ./server:/server
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /client/node_modules
            - ./client:/client
    worker:
        env_file: ./.env
        ports:
            - '8080:8080'
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /worker/node_modules
            - ./worker:/worker